# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import route_pb2 as route__pb2


class RouteGuideStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetTimings = channel.stream_stream(
                '/log_analysis.RouteGuide/GetTimings',
                request_serializer=route__pb2.pure_data.SerializeToString,
                response_deserializer=route__pb2.structured_data.FromString,
                )


class RouteGuideServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetTimings(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RouteGuideServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetTimings': grpc.stream_stream_rpc_method_handler(
                    servicer.GetTimings,
                    request_deserializer=route__pb2.pure_data.FromString,
                    response_serializer=route__pb2.structured_data.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'log_analysis.RouteGuide', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RouteGuide(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetTimings(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/log_analysis.RouteGuide/GetTimings',
            route__pb2.pure_data.SerializeToString,
            route__pb2.structured_data.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
