# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: route.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0broute.proto\x12\x0clog_analysis\"Z\n\x0fstructured_data\x12\x14\n\x0cservice_name\x18\x01 \x01(\t\x12\x17\n\x0fuptime_duration\x18\x02 \x01(\x02\x12\x18\n\x10request_duration\x18\x03 \x01(\x02\"i\n\tpure_data\x12/\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32!.log_analysis.pure_data.DataEntry\x1a+\n\tDataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x32V\n\nRouteGuide\x12H\n\nGetTimings\x12\x17.log_analysis.pure_data\x1a\x1d.log_analysis.structured_data(\x01\x30\x01\x62\x06proto3')



_STRUCTURED_DATA = DESCRIPTOR.message_types_by_name['structured_data']
_PURE_DATA = DESCRIPTOR.message_types_by_name['pure_data']
_PURE_DATA_DATAENTRY = _PURE_DATA.nested_types_by_name['DataEntry']
structured_data = _reflection.GeneratedProtocolMessageType('structured_data', (_message.Message,), {
  'DESCRIPTOR' : _STRUCTURED_DATA,
  '__module__' : 'route_pb2'
  # @@protoc_insertion_point(class_scope:log_analysis.structured_data)
  })
_sym_db.RegisterMessage(structured_data)

pure_data = _reflection.GeneratedProtocolMessageType('pure_data', (_message.Message,), {

  'DataEntry' : _reflection.GeneratedProtocolMessageType('DataEntry', (_message.Message,), {
    'DESCRIPTOR' : _PURE_DATA_DATAENTRY,
    '__module__' : 'route_pb2'
    # @@protoc_insertion_point(class_scope:log_analysis.pure_data.DataEntry)
    })
  ,
  'DESCRIPTOR' : _PURE_DATA,
  '__module__' : 'route_pb2'
  # @@protoc_insertion_point(class_scope:log_analysis.pure_data)
  })
_sym_db.RegisterMessage(pure_data)
_sym_db.RegisterMessage(pure_data.DataEntry)

_ROUTEGUIDE = DESCRIPTOR.services_by_name['RouteGuide']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PURE_DATA_DATAENTRY._options = None
  _PURE_DATA_DATAENTRY._serialized_options = b'8\001'
  _STRUCTURED_DATA._serialized_start=29
  _STRUCTURED_DATA._serialized_end=119
  _PURE_DATA._serialized_start=121
  _PURE_DATA._serialized_end=226
  _PURE_DATA_DATAENTRY._serialized_start=183
  _PURE_DATA_DATAENTRY._serialized_end=226
  _ROUTEGUIDE._serialized_start=228
  _ROUTEGUIDE._serialized_end=314
# @@protoc_insertion_point(module_scope)
